kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jenkins-devlopment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkins-devlopment
    spec:
      containers:
      - name: jenkins-devlopment
        image: jenkins/jenkins:lts
        env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        envFrom:
        - configMapRef:
            name: plugins
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/jenkins_home/
          name: vol1
      dnsConfig:
        searches:
        - <DNS>
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: <PwD>
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: jenkins
