kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jenkins-devlopment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkins-devlopment
    spec:
      containers:
      - name: jenkins-devlopment
        image: jenkins/jenkins:lts
        env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        envFrom:
        - configMapRef:
            name: plugins
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
    
