groups:
- name: Jenkins-Slaves
  rules:
  - alert: LinuxServerDown 
    expr: up{job="Jenkins-Slaves"} == 0
    labels:
      severity: critical
    annotations:
      summary: Jenkins Node Server Down
