apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: 
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
    - job_name: prometheus
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9090
    - job_name: 'Jenkins-nodes'
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      scheme: https
      tls_config:
        insecure_skip_verify: true
      metrics_path: /prometheus
      static_configs:
      - targets:
        - <JenkinsServer>
